# Aggregation Functions in NumPy

### What Are Aggregation Functions?

Aggregation functions take an entire array (or a part of it) and **reduce** it to a single summary value. They’re super important in data analysis and machine learning because they give you insights like totals, averages, max/min values, and distributions in your data.

### Common Aggregation Functions

| Function | Description | Example |
| --- | --- | --- |
| `np.sum()` | Sum of all elements | Sum all numbers in an array |
| `np.prod()` | Product of all elements | Multiply all numbers |
| `np.mean()` | Average (mean) of elements | Compute average value |
| `np.median()` | Median (middle value when sorted) | Compute middle value |
| `np.min()` | Minimum value | Smallest number |
| `np.max()` | Maximum value | Largest number |
| `np.var()` | Variance (spread of data) | Average squared deviation from the mean |
| `np.std()` | Standard deviation (spread of data) | Square root of variance |

### Example

In [1]:
import numpy as np

arr = np.array([2, 4, 6, 8, 10])

print("Sum:", np.sum(arr))           
print("Product:", np.prod(arr))     
print("Mean:", np.mean(arr))        
print("Median:", np.median(arr))    
print("Min:", np.min(arr))          
print("Max:", np.max(arr))          
print("Variance:", np.var(arr))     
print("Std Deviation:", np.std(arr))

Sum: 30
Product: 3840
Mean: 6.0
Median: 6.0
Min: 2
Max: 10
Variance: 8.0
Std Deviation: 2.8284271247461903


### Axis Parameter for Aggregation

For multi-dimensional arrays, you can aggregate across **rows** or **columns** using the `axis` parameter:

In [2]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])

print("Sum over columns (axis=0):", np.sum(matrix, axis=0))
print("Sum over rows (axis=1):", np.sum(matrix, axis=1)) 

Sum over columns (axis=0): [5 7 9]
Sum over rows (axis=1): [ 6 15]


### Exercises

Q1. Create a NumPy array `[3, 5, 7, 9, 11]` and compute its sum, mean, and product.

In [3]:
arr = np.array([3, 5, 7, 9, 11])

print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Product:", np.prod(arr))

Sum: 35
Mean: 7.0
Product: 10395


Q2. Create a 2x3 matrix from 10 - 60  and calculate the column-wise mean and row-wise sum.

In [4]:
matrix = np.array([[10, 20, 30],
                   [40, 50, 60]])

print("Sum over columns (axis=0):", np.sum(matrix, axis=0))
print("Sum over rows (axis=1):", np.sum(matrix, axis=1))

Sum over columns (axis=0): [50 70 90]
Sum over rows (axis=1): [ 60 150]


Q3. Generate a random 5x5 matrix and find the maximum and minimum values overall, and along each axis.

In [ ]:
matrix = np.random.randint(0, 101, size=(5, 5))
print("Matrix:\n", matrix)

max_val = np.max(matrix)
min_val = np.min(matrix)
print(f"Overall max: {max_val}")
print(f"Overall min: {min_val}")

max_axis0 = np.max(matrix, axis=0)
min_axis0 = np.min(matrix, axis=0)
print(f"Max values along columns: {max_axis0}")
print(f"Min values along columns: {min_axis0}")

max_axis1 = np.max(matrix, axis=1)
min_axis1 = np.min(matrix, axis=1)
print(f"Max values along rows: {max_axis1}")
print(f"Min values along rows: {min_axis1}")

Matrix:
 [[ 11  11  24  93  95]
 [ 73  59  11  46  61]
 [ 22  84  21 100  87]
 [ 66  57  73  55  47]
 [ 66  77  33  99  14]]
Overall max: 100
Overall min: 11
Max values along columns: [ 73  84  73 100  95]
Min values along columns: [11 11 11 46 14]
Max values along rows: [ 95  73 100  73  99]
Min values along rows: [11 11 21 47 14]


Q4. Calculate the variance and standard deviation of the array `[10, 20, 30, 40, 50]`.

In [6]:
arr = np.array([10, 20, 30, 40, 50])
variance = np.var(arr)
standard_deviation = np.std(arr)

print(f'Standard deviation: {standard_deviation}')
print(f'Variance: {variance}')

Standard deviation: 14.142135623730951
Variance: 200.0


### Summary

Aggregation functions in NumPy are powerful tools that reduce large arrays of data into meaningful summary values, such as sums, means, products, minimums, maximums, variances, and standard deviations. These functions help us understand the overall characteristics and distribution of data quickly and efficiently, which is essential for tasks like data preprocessing, analysis, and model evaluation in AI and machine learning. For example, calculating the sum or mean of a dataset can reveal total quantities or average trends, while variance and standard deviation provide insights into data spread and variability. When working with multi-dimensional data, aggregation can be performed across specific axes—such as rows or columns—allowing flexible and precise summaries. By mastering aggregation functions, you gain the ability to transform raw numerical data into actionable insights, making them fundamental building blocks in any AI or data science workflow.