# Array Shape, Dimensions & Reshaping

### What Are Shape and Dimensions in NumPy?

In NumPy, every array has an internal structure defined by **its shape and number of dimensions**. This structure determines how data is stored, accessed, and processed — and it becomes especially important when working on **AI/ML tasks**, where the data must match strict model input shapes.

- **`.shape`**: A tuple showing the size along each axis. For example, `(3, 2)` means 3 rows and 2 columns.
- **`.ndim`**: The number of axes (or dimensions). A scalar has `ndim=0`, a 1D array has `ndim=1`, and so on.
- **`.size`**: Total number of elements in the array (product of all shape values).

Example:

In [1]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)
print(arr.ndim)
print(arr.size)

(2, 3)
2
6


### Reshaping Arrays with `.reshape()`

→ NumPy provides `.reshape()` to change an array’s structure without altering its contents. For example, an array of shape `(6,)` can be reshaped to `(2, 3)`, `(3, 2)`, or `(1, 6)`, as long as the **total number of elements remains constant**.

In [2]:
a = np.arange(6)
b = a.reshape((2, 3))
print(a,"\n")
print(b)

[0 1 2 3 4 5] 

[[0 1 2]
 [3 4 5]]


It also supports **auto-inferred shapes** using `-1`:

In [3]:
print(a.reshape((-1, 2)))

[[0 1]
 [2 3]
 [4 5]]


Invalid reshapes (like turning a 6-element array into a (4,2)) will raise an error.

## Why Shape & Dimensions Matter in AI/ML

In machine learning, **data shape is everything**:

- Neural networks require inputs with fixed shapes: `(batch_size, features)` or `(batch, height, width, channels)`
- A 28x28 grayscale image is usually reshaped from `(28, 28)` to `(784,)` before passing to dense layers
- Batch processing requires shapes like `(32, 784)` for 32 images at once
- RNNs expect 3D shapes like `(batch, timesteps, features)`
- CNNs expect 4D shapes like `(batch, height, width, channels)`

We’ll constantly use `.reshape()` to prepare data for models, whether we're feeding images, time series, or vectors.

### Key Takeaways

| Attribute | Description | Code Example | Output |
| --- | --- | --- | --- |
| `shape` | Structure of array | `a.shape` | `(2, 3)` |
| `ndim` | Number of axes | `a.ndim` | `2` |
| `size` | Total elements | `a.size` | `6` |
| `reshape()` | Change shape while preserving data | `a.reshape((3, 2))` | Valid if sizes match |
| `reshape(-1, ...)` | Auto-calculate shape | `a.reshape(-1)` | Flattened |

### Exercises

Q1. Create a 2D array of shape (3, 4), print its shape, dimensions, and size, then flatten it to 1D using `.reshape(-1)` and print the new shape and dimension.

In [4]:
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

print("Shape:", a.shape)       
print("Dimensions:", a.ndim)   
print("Size:", a.size)         

a_flat = a.reshape(-1)
print("Flattened:", a_flat)
print("New Shape:", a_flat.shape)
print("New Dimensions:", a_flat.ndim)

Shape: (3, 4)
Dimensions: 2
Size: 12
Flattened: [ 1  2  3  4  5  6  7  8  9 10 11 12]
New Shape: (12,)
New Dimensions: 1


Q2. Create a 1D array of 24 elements using `np.arange()`, reshape it to (4, 6), then to (2, 3, 4), and verify that all reshaped arrays contain 24 elements.

In [5]:
b = np.arange(24)

b_2d = b.reshape(4, 6)

b_3d = b.reshape(2, 3, 4)

print("Original shape:", b.shape)
print("2D shape:", b_2d.shape)
print("3D shape:", b_3d.shape)
print("Total elements:", b.size)

Original shape: (24,)
2D shape: (4, 6)
3D shape: (2, 3, 4)
Total elements: 24


### Summary

In NumPy, understanding array shape, dimensions, and reshaping is fundamental for any data science or AI/ML workflow. Every array has a `.shape` that defines its structure (like rows and columns), an `.ndim` that tells us how many dimensions (or axes) it has, and a `.size` which tells us the total number of elements. These attributes help us manage and manipulate data precisely. The `.reshape()` method allows us to change the structure of an array without changing its data, as long as the total number of elements remains the same. This is especially important in machine learning, where model input requirements are strict — for example, image data might need reshaping from `(28, 28)` to `(784,)`, or adding batch dimensions like `(batch, features)` or `(batch, height, width, channels)` for deep learning models. We can also use `-1` in `.reshape()` to let NumPy automatically calculate the correct dimension, which is very handy when preprocessing large datasets. Reshaping is not just about format — it’s about ensuring compatibility with AI models and enabling efficient computation. Overall, mastering `.shape`, `.ndim`, and `.reshape()` is essential for building clean, bug-free, and production-ready machine learning pipelines.