# Array Data Types & Type Conversion

### What is `dtype` in NumPy?

In NumPy, every array has a data type (`dtype`), which determines the kind of values it can hold—such as integers (`int32`, `int64`), floating points (`float32`, `float64`), booleans (`bool`), and even complex numbers or strings.

Knowing the data type of an array is essential for **memory efficiency**, **processing speed**, and **compatibility** with machine learning frameworks. For example, an array with `int32` will take less memory than `int64`, and `float32` is commonly used in deep learning models due to GPU optimization.

We can check an array’s data type using:

In [1]:
import numpy as np

a = np.array([1, 2, 3])
print(a.dtype)

int64


### Type Conversion Using `.astype()`

NumPy allows us to **convert data types** using `.astype()` method. This is especially useful when:

- Preparing data for a model (e.g., converting integers to floats).
- Compressing memory usage.
- Avoiding type mismatch errors.

In [2]:
a = np.array([1, 2, 3])

# Convert to float
a_float = a.astype(float)
print(a_float)

# Convert to bool
a_bool = a.astype(bool)
print(a_bool)

# Convert float to int (decimal will be dropped)
a_back = a_float.astype(int)
print(a_back)

[1. 2. 3.]
[ True  True  True]
[1 2 3]


### Common Data Type Conversion Operations in NumPy

| **Operation** | **Description** | **Code** | **Result** |
| --- | --- | --- | --- |
| Check type | Show data type | `a.dtype` | `int64` |
| Convert to float | Type conversion | `a.astype(float)` | `[1.0, 2.0, 3.0]` |
| Int to bool | 0=False, others=True | `a.astype(bool)` | `[True, True, True]` |
| Float to int | Drops decimals | `a.astype(int)` | `[1, 2, 3]` |
| Invalid cast | String to int (not allowed) | ❌ `a.astype(int)` | `Error` |

### Exercises

Q1. Create a 1D array containing values from 1 to 5
- Print the data type of `a` using `.dtype`

In [3]:
a = np.array([1, 2, 3, 4, 5])
print(a.dtype)

int64


Q2. Convert the array `a` to the following data types using `.astype()`

- a boolean array
- a float array

In [4]:
print(a.astype(bool))
print(a.astype(float))

[ True  True  True  True  True]
[1. 2. 3. 4. 5.]


Q3. Create an array with `[1.9, 0.0, 0.5, 3.7]` items and convert it to integers and boolean.

In [5]:
b = np.array([1.9, 0.0, 0.5, 3.7])
print(b.astype(int))
print(b.astype(bool))

[1 0 0 3]
[ True False  True  True]


### Summary

In NumPy, understanding and using `dtype` (data type) is crucial in AI and machine learning workflows. Data types affect **memory efficiency**, **performance**, and **precision**. For example, using `float32` instead of `float64` reduces memory usage significantly, which is important when working with large datasets or running models on GPUs. Most deep learning frameworks like TensorFlow and PyTorch are optimized for `float32`, making it a standard for model training. Also, selecting the appropriate type avoids issues like **overflow**, **underflow**, or **loss of precision**. we can check a NumPy array’s data type using `a.dtype`, and convert it using `.astype()` — such as converting an `int` array to `float`, or a `float` array to `bool`. For example, an array `[1, 2, 3]` can be transformed to `[1.0, 2.0, 3.0]` using `.astype(float)`, and then to `[True, True, True]` using `.astype(bool)`. These conversions are useful in preprocessing pipelines or while passing data to machine learning models. However, be cautious of **lossy conversions** — like converting float to int, which drops the decimal part. Overall, `dtype` and type conversion are powerful tools that must be used wisely for **high-performance, error-free AI applications**. In real ML pipelines, using the right `dtype` like `float32` not only ensures **GPU compatibility** but also **optimizes memory usage and training performance** for large-scale models.