# Array Indexing, Slicing & Boolean Indexing

### What is indexing and Slicing?

In NumPy, **indexing** allows us to access specific elements from an array, and **slicing** allows us to extract a portion of the array. These are essential tools for manipulating and analyzing data efficiently.

Unlike Python lists, NumPy arrays support more powerful indexing, including **boolean** and **fancy indexing**, which help us extract or modify data based on conditions or index lists.

### Indexing in NumPy:

Indexing is the process of selecting specific elements from a NumPy array using their position (index). In 1D arrays, we use a single index like `a[2]`. In 2D arrays, we use a pair of indices like `a[row, column]` to access individual elements.

In [1]:
import numpy as np

a = np.array([[10, 20, 30], [40, 50, 60]])
print(a[0, 1])
print(a[1][2])

20
60


Visual Representation of `a`:

![Image 1](Image/Image1.png)

### Negative Indexing:

Negative indexing allows us to access elements from the end of the array. For example, `a[-1]` gives the last element, `a[-2]` gives the second last.

In [2]:
a = np.array([10, 20, 30, 40, 50])
print(a[-1])

50


Visual Representation of `a`:

![Image 2](Image/Image2.png)

For 2D arrays:

In [3]:
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b[-1, -1]) 
print(b[-2, -3])  

6
1


Visual Representation of `b`:

![Image 3](Image/Image3.png)

![Image 4](Image/Image4.png)

### Slicing Arrays:

Slicing is used to extract a portion or range of elements from an array using the syntax `[start:stop:step]`. This can be applied to 1D, 2D, or higher-dimensional arrays.

1D slicing:

In [4]:
a = np.array([10, 20, 30, 40, 50])
print(a[1:4])
print("Reverse: ",a[::-1])

[20 30 40]
Reverse:  [50 40 30 20 10]


Visual Representation of `a`:

![Image 5](Image/Image5.png)

2D slicing:

In [5]:
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b[0:2, 1:])

[[2 3]
 [5 6]]


Visual Representation of `b`: 

![Image 6](Image/Image6.png)

Slicing with Steps:

In [6]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(a[::2])     # Every 2nd value → [0 2 4 6 8]
print(a[2:8:2])   # From index 2 to 8, step 2 → [2 4 6]

[0 2 4 6 8]
[2 4 6]


Visual Representation of `a`:

![Image 7](Image/Image7.png)

![Image 8](Image/Image8.png)

### Boolean Indexing:

Boolean indexing selects elements based on conditions. For example, `a[a > 5]` returns all elements greater than 5. We can also combine multiple conditions using `&`, `|`, `~`.

In [7]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a[a > 3])

[4 5 6]


Visual Representation of `a`:

![Image 9](Image/Image9.png)

We can even use combined conditions:

In [8]:
print(a[(a > 2) & (a < 6)])

[3 4 5]


Visual Representation of `a`:

![Image 10](Image/Image10.png)

Boolean Indexing Reference Table:

| Condition                    | Operator/Function    | Description             | Code Example                 | Result                   |
|------------------------------|---------------------|-------------------------|------------------------------|--------------------------|
| Greater than 3               | `>`                 | Elements greater than 3 | `a[a > 3]`                   | `[4, 5, 6, 7, 8, 9]`     |
| Less than 8                 | `<`                 | Elements less than 8    | `a[a < 8]`                   | `[1, 2, 3, 4, 5, 6, 7]`  |
| Equal to 5                  | `==`                | Elements equal to 5     | `a[a == 5]`                  | `[5]`                    |
| Not equal to 5              | `!=`                | Exclude the value 5     | `a[a != 5]`                  | `[1, 2, 3, 4, 6, 7, 8, 9]`|
| Greater than or equal       | `>=`                | Elements ≥ 5            | `a[a >= 5]`                  | `[5, 6, 7, 8, 9]`        |
| Less than or equal          | `<=`                | Elements ≤ 5            | `a[a <= 5]`                  | `[1, 2, 3, 4, 5]`        |
| **AND Conditions**          |                     |                         |                              |                          |
| Greater than 3 AND less than 8 | `&`              | Select values between 4 and 7 | `a[(a > 3) & (a < 8)]`   | `[4, 5, 6, 7]`           |
| Greater than 3 AND less than 8 AND not 5 | `&`      | Between 4 and 7 excluding 5 | `a[(a > 3) & (a < 8) & (a != 5)]` | `[4, 6, 7]`        |
| Greater than 7 AND even     | `&` and `%`          | Select even values after 7 | `a[(a > 7) & (a % 2 == 0)]` | `[8]`                    |
| **OR Conditions**           |                     |                         |                              |                          |
| Less than 4 OR greater than 7 | `\|`               | Select < 4 or > 7       | `a[(a < 4) \| (a > 7)]`      | `[1, 2, 3, 8, 9]`        |
| Equal to 2 OR equal to 8    | `\|`                 | Select specific values  | `a[(a == 2) \| (a == 8)]`    | `[2, 8]`                 |
| **NOT Conditions**          |                     |                         |                              |                          |
| NOT equal to 5              | `~`                 | Inverse of condition    | `a[~(a == 5)]`               | `[1, 2, 3, 4, 6, 7, 8, 9]`|
| NOT greater than 5          | `~`                 | Inverse: ≤ 5            | `a[~(a > 5)]`                | `[1, 2, 3, 4, 5]`        |
| **NumPy Logical Functions** |                     |                         |                              |                          |
| Logical AND                 | `np.logical_and()`  | Same as `(a > 3) & (a < 8)` | `a[np.logical_and(a > 3, a < 8)]` | `[4, 5, 6, 7]`    |
| Logical OR                  | `np.logical_or()`   | Same as `(a < 4) \| (a > 7)` | `a[np.logical_or(a < 4, a > 7)]` | `[1, 2, 3, 8, 9]`   |
| Logical NOT                 | `np.logical_not()`  | Same as `~(a == 5)`     | `a[np.logical_not(a == 5)]`  | `[1, 2, 3, 4, 6, 7, 8, 9]`|
| **Special Conditions**      |                     |                         |                              |                          |
| Even numbers                | `%`                 | Divisible by 2          | `a[a % 2 == 0]`              | `[2, 4, 6, 8]`           |
| Odd numbers                 | `%`                 | Not divisible by 2      | `a[a % 2 != 0]`              | `[1, 3, 5, 7, 9]`        |
| Divisible by 3             | `%`                 | Multiples of 3          | `a[a % 3 == 0]`              | `[3, 6, 9]`              |
| In a list of values         | `np.isin()`         | Check membership        | `a[np.isin(a, [2, 5, 8])]`   | `[2, 5, 8]`              |

Important Notes:

1. **Parentheses are crucial** for complex conditions: `(a > 3) & (a < 8)` not `a > 3 & a < 8`
2. **Use `&` for AND**, not `and`
3. **Use `|` for OR**, not `or`
4. **Use `~` for NOT**, not `not`
5. **NumPy logical functions** can be more readable for complex conditions
6. **Boolean indexing returns a new array**, original array is unchanged

### Fancy Indexing:

Fancy indexing means accessing elements using lists or arrays of indices, like `a[[0, 2, 4]]`. It also works in multi-dimensional arrays.


In [9]:
a = np.array([10, 20, 30, 40, 50])
idx = [1, 3, 4]
print(a[idx])

[20 40 50]


Visual Representation of `a`:

![Image 11](Image/Image11.png)

We can use this in multi-dimensional arrays too:

In [10]:
b = np.array([[1, 2], [3, 4], [5, 6]])
print(b[[0, 2], [1, 0]])

[2 5]


Visual Representation of `b`:

![Image 12](Image/Image12.png)

### Advanced Fancy Indexing:

In [11]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

rows = [0, 2]
cols = [1, 2]

print(matrix[rows],"\n")    # Select specific rows
print(matrix[:, cols])      # Select specific columns from all rows

[[1 2 3]
 [7 8 9]] 

[[2 3]
 [5 6]
 [8 9]]


Visual Representation of `matrix`:

![Image 13](Image/Image13.png)

![Image 14](Image/Image14.png)

### Modifying Arrays via Indexing

We can change the values of specific elements using indexing. For example:

- `a[0] = 100` changes the first element
- `a[a > 5] = 0` modifies all values greater than 5

In [12]:
#modify array via indexing
a = np.array([1, 2, 3, 4, 5, 6])

# Single element
a[0] = 100
print(a) 

a = np.array([1, 2, 3, 4, 5, 6])
# Slicing
a[1:4] = [20, 30, 40]
print(a)

a = np.array([1, 2, 3, 4, 5, 6])
# Boolean
a[a > 50] = 0
print(a)

a = np.array([1, 2, 3, 4, 5, 6])
# Even numbers
a[a % 2 == 0] = -1
print(a)

[100   2   3   4   5   6]
[ 1 20 30 40  5  6]
[1 2 3 4 5 6]
[ 1 -1  3 -1  5 -1]


### Common Pitfalls

These are mistakes that commonly occur while using indexing:

- Using `and`, `or` instead of `&`, `|`
- Forgetting parentheses in boolean expressions
- Expecting fancy/boolean indexing to create views (they make copies!)
- Trying to index beyond array dimensions (IndexError)

### Exercises

Q1. Create a 3×4 array filled with values from 10 to 120.

1. Access and print the value `60` using standard indexing.
2. Slice the array to extract a subarray that contains the **last two rows** and the **last two columns**.
3. Print the **first row** in reverse order using slicing.

In [13]:
arr = np.array([[10, 20, 30, 40], 
                [50, 60, 70, 80], 
                [90, 100, 110, 120]])

print(arr[1:2, 1:2],"\n")
print(arr[1:,2:],"\n")
print(arr[0:1, ::-1])

[[60]] 

[[ 70  80]
 [110 120]] 

[[40 30 20 10]]


Q2. Create a 1D NumPy array with values from 1 to 20.

1. Use **negative indexing** to extract the **last 5 elements in reverse order**.
2. Slice the array to return every **3rd element starting from index -2 and going backwards**.

In [14]:
a = np.arange(1, 21)
print(a[-5:][::-1])
print(a[-2::-3])

[20 19 18 17 16]
[19 16 13 10  7  4  1]


Q3. Create a 1D NumPy array with values from 1 to 20. Use **boolean indexing** to extract:

1. All elements that are divisible by both **2 and 3**.
2. All elements that are **not between 8 and 15**, inclusive.
3. All elements that are either **less than 5** or **greater than 18**.

In [15]:
a = np.arange(1, 21)
print(a[np.logical_and(a % 3 == 0, a % 2 == 0)])
print(a[np.logical_not(np.logical_and(a >= 8, a <= 15))])
print(a[np.logical_or(a < 5, a > 18)])

[ 6 12 18]
[ 1  2  3  4  5  6  7 16 17 18 19 20]
[ 1  2  3  4 19 20]


Q4. Create a 4x4 array filled with values from 1 to 16.

1. Use **fancy indexing** to extract the **diagonal elements** (1, 6, 11, 16).
2. Use fancy indexing to extract the values at these positions:
    - Row 0, Column 3
    - Row 2, Column 1
    - Row 3, Column 0

In [16]:
matrix = np.array([[ 1,  2,  3,  4],
                   [ 5,  6,  7,  8],
                   [ 9, 10, 11, 12],
                   [13, 14, 15, 16]])

print(matrix[[0, 1, 2, 3], [0, 1, 2, 3]])
print(matrix[[0,2,3],[3,1,0]])

[ 1  6 11 16]
[ 4 10 13]


Q5.  Create a 1D NumPy array with values from 0 to 19. 

1. Modify the array so that all **even numbers** are replaced with `-1`.
2. Replace all values **greater than 10** with their **squares**.
3. Using **fancy indexing**, update the values at indices `[1, 5, 10, 15]` and set them to `999`.

In [17]:
a = np.arange(20)
a[a % 2 == 0] = -1
print(a,"\n")

a = np.arange(20)
a[a > 10] = a[a > 10] ** 2
print(a,"\n")

a = np.arange(20)
idx = [1,5,10,15]
a[idx] = 999
print(a)

[-1  1 -1  3 -1  5 -1  7 -1  9 -1 11 -1 13 -1 15 -1 17 -1 19] 

[  0   1   2   3   4   5   6   7   8   9  10 121 144 169 196 225 256 289
 324 361] 

[  0 999   2   3   4 999   6   7   8   9 999  11  12  13  14 999  16  17
  18  19]


### Summary

In NumPy, indexing and slicing are essential tools for accessing and manipulating array elements efficiently. **Indexing** refers to selecting individual elements using their positions—for example, `arr[1, 2]` accesses the element at row 1, column 2 in a 2D array. **Negative indexing** allows selection from the end, such as `arr[-1]` for the last element. **Slicing**, using the `[start:stop:step]` syntax, lets us extract subarrays or sequences of elements, making it easy to work with ranges or reverse arrays. Beyond basic indexing, NumPy offers **boolean indexing**, where we filter data based on conditions like `arr[arr > 5]`, and we can combine conditions using `&`, `|`, and `~` to construct powerful selection logic. This is particularly useful in data analysis, where selecting data that meets specific criteria is common. **Fancy indexing** goes a step further by allowing selection of elements using lists or arrays of indices, enabling extraction of scattered or non-contiguous values. Finally, all these techniques also support modification—using indexing or boolean conditions, we can directly update values within an array. However, it’s important to be cautious about common mistakes like using `and/or` instead of `&/|`, or assuming boolean/fancy indexing returns views (they return copies). Together, these advanced indexing techniques make NumPy a powerful tool for efficient and expressive data manipulation in scientific computing and AI workflows.
