# Broadcasting & Vectorized Operations

### What is Broadcasting in NumPy?

Broadcasting in NumPy is a powerful method that allows arrays of **different shapes** to be used in **arithmetic operations** without writing loops. It automatically stretches (or broadcasts) smaller arrays to match the shape of larger ones during calculations — without actually copying the data. This leads to faster, more readable code.

Broadcasting follows strict rules but removes the need to manually reshape or replicate arrays.

In [1]:
import numpy as np

a = np.array([1, 2, 3])
b = 10
print(a + b)

[11 12 13]


Here, `b` is a scalar but is broadcasted to match the shape of `a`.

### Broadcasting Rules

1. If arrays have different numbers of dimensions, the smaller one is **prepended with 1s** on the left.
2. Arrays are **compatible** if for each dimension the sizes are either equal or one of them is 1.
3. If arrays are compatible, NumPy **broadcasts** them to a common shape and performs element-wise operations.

In [2]:
A = np.array([[1], [2], [3]])   # shape (3, 1)
B = np.array([10, 20, 30])      # shape (3,)
C = A + B                       # Broadcasts B to shape (3, 3)
print(C)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


### Example

In [3]:
# Add scalar to array
arr = np.array([1, 2, 3])
print(arr + 5)  # [6 7 8]

# Add 1D array to 2D array (broadcast row-wise)
mat = np.array([[1, 2, 3], [4, 5, 6]])
row = np.array([10, 20, 30])
print(mat + row)

[6 7 8]
[[11 22 33]
 [14 25 36]]


### What Is Vectorization?

Vectorization means using **array operations** instead of **loops** to perform calculations. It’s faster and more efficient because NumPy uses C under the hood.

In [4]:
# With loop
result = []
for i in range(100):
    result.append(i * 2)
print("With loop: ",result)

# Vectorized version
arr = np.arange(100)
result = arr * 2
print("\nVectorized version: ",result)

With loop:  [0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182, 184, 186, 188, 190, 192, 194, 196, 198]

Vectorized version:  [  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100 102 104 106
 108 110 112 114 116 118 120 122 124 126 128 130 132 134 136 138 140 142
 144 146 148 150 152 154 156 158 160 162 164 166 168 170 172 174 176 178
 180 182 184 186 188 190 192 194 196 198]


This vectorized approach is much faster and leads to cleaner code.

### Example

In [5]:
arr = np.arange(10)
print("Original array:", arr)

# Square each element using vectorized operation
squared = arr ** 2
print("Squared array:", squared)

Original array: [0 1 2 3 4 5 6 7 8 9]
Squared array: [ 0  1  4  9 16 25 36 49 64 81]


### Benefits in AI & Machine Learning

- **Faster Training**: Operations like normalization, loss calculation, and gradient updates are all vectorized for speed.
- **Cleaner Code**: Avoids long loops when working with datasets.
- **Memory Efficiency**: Broadcasting avoids creating huge intermediate arrays.

### Exercises

Q1. Create a 1D array of numbers from 10 to 15 and broadcast-add 10 to each element.

In [6]:
a = np.arange(10, 16)
b = a + 10
print(b)

[20 21 22 23 24 25]


Q2. Create a 2D array of shape (3, 3) and subtract a 1D array `[1, 2, 3]` from each row using broadcasting.

In [7]:
c = np.arange(1, 10).reshape(3, 3)
d = np.array([1, 2, 3])
e = c - d
print(e)

[[0 0 0]
 [3 3 3]
 [6 6 6]]


Q3. Create a 1D array from 1 to 100. Square each element using vectorized operations.

In [8]:
f = np.arange(1, 101)
g = f ** 2
print(g)

[    1     4     9    16    25    36    49    64    81   100   121   144
   169   196   225   256   289   324   361   400   441   484   529   576
   625   676   729   784   841   900   961  1024  1089  1156  1225  1296
  1369  1444  1521  1600  1681  1764  1849  1936  2025  2116  2209  2304
  2401  2500  2601  2704  2809  2916  3025  3136  3249  3364  3481  3600
  3721  3844  3969  4096  4225  4356  4489  4624  4761  4900  5041  5184
  5329  5476  5625  5776  5929  6084  6241  6400  6561  6724  6889  7056
  7225  7396  7569  7744  7921  8100  8281  8464  8649  8836  9025  9216
  9409  9604  9801 10000]


Q4. Normalize a NumPy array `[10, 20, 30, 40, 50]` using vectorized operations (subtract mean and divide by std deviation).

In [9]:
h = np.array([10, 20, 30, 40, 50])
mean_h = np.mean(h)
std_h = np.std(h)
normalized_h = (h - mean_h) / std_h
print(normalized_h)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


### Summary

Broadcasting and vectorization are core performance boosters in NumPy that allow us to write AI/ML code that's **clean, efficient, and fast**. Broadcasting enables us to perform operations between arrays of different shapes by automatically expanding one of them to match the shape of the other — without copying data. This means we can easily add a scalar to an array, a 1D row vector to a 2D matrix, or even match shapes in more complex ways. For instance, a shape of `(3, 1)` can be broadcast with `(1, 3)` to produce a `(3, 3)` result.

On the other hand, vectorization helps eliminate the use of Python loops altogether. Instead of manually iterating through elements, we perform operations on entire arrays. This isn’t just syntactic sugar — it’s **faster and more memory-efficient**, and it scales better for large datasets used in training AI models. Deep learning libraries like TensorFlow, PyTorch, and JAX heavily rely on broadcasting and vectorized operations under the hood. Whether we're applying transformations, calculating loss functions, or doing matrix operations — broadcasting and vectorization allow us to write code that’s both powerful and elegant.