# Introduction to NumPy and Creating Arrays

## What is NumPy?

NumPy (Numerical Python) is a fundamental packages for scientific computing in Python. It helps us work with **multidimensional arrays and matrices**, along with a wide collection of **mathematical functions** to operate on these arrays.

While Python list are flexible, they are slow for large datasets. That’s where NumPy shines — it’s **faster, more memory-efficient**, and supports **vectorized operations**, which means we can perform tasks on entire arrays without writing loops.

### Why Do We Use NumPy?

Here’s why we prefer NumPy for data science and AI work:

- **Speed & Performance**: NumPy arrays (ndarrays) are way faster than Python lists because they store data in contiguous blocks of memory with fixed types.
- **Less Memory Usage**: Python lists store each item as a full Python object with overhead. NumPy arrays skip that and store only raw values.
- **Broadcasting & Vectorization**: We can perform operations on whole arrays without writing slow loops.
- **Foundation for AI/ML Libraries**: Libraries like Pandas, TensorFlow, PyTorch, and Scikit-learn are built on top of NumPy.
- **Powerful I/O Capabilities**: We can load, save, and manipulate data easily with built-in tools.

### Importing NumPy

To start using NumPy, we need to import it first:

In [1]:
import numpy as np

The convention `np` keeps our code short and readable.

### Creating NumPy Arrays

**From Python List:**

In [2]:
nums = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
arr = np.array(nums)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


**Multidimensional Arrays:**

In [3]:
two_d = np.array([[1, 2], [3, 4]])
print(two_d)

[[1 2]
 [3 4]]


**Using NumPy Functions:**

In [4]:
print('1.', np.zeros((2, 3)), '\n')        # All zeros
print('2.', np.ones((3, 3)), '\n')         # All ones
print('3.', np.full((2, 2), 7), '\n')      # Filled with 7
print('4.', np.eye(3), '\n')               # Identity matrix
print('5.', np.arange(0, 10, 2), '\n')     # Range with step
print('6.', np.linspace(0, 1, 5), '\n')    # Evenly spaced
print('7.', np.empty((2,3)))               # Uninitialized

1. [[0. 0. 0.]
 [0. 0. 0.]] 

2. [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 

3. [[7 7]
 [7 7]] 

4. [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

5. [0 2 4 6 8] 

6. [0.   0.25 0.5  0.75 1.  ] 

7. [[0. 0. 0.]
 [0. 0. 0.]]


**Inspecting Arrays:**

In [5]:
numbers = [1, 2, 3, 4]
array = np.array(numbers)

print('1.', array.shape)       # (rows, columns)
print('2.', array.ndim)        # Number of dimensions
print('3.', array.size)        # Total number of elements
print('4.', array.dtype)       # Data type (output as dtype object) int64
print('5.', array.dtype.name)  # Name of the dtype (output as string) 'int64'

1. (4,)
2. 1
3. 4
4. int64
5. int64


### Data Types in NumPy

NumPy supports powerful data types:

| Data Type | Description |
| --- | --- |
| `np.int64` | 64-bit integer |
| `np.float32` | 32-bit float |
| `np.complex` | Complex numbers |
| `np.bool_` | Boolean (True/False) |
| `np.string_` | Fixed-length ASCII strings |
| `np.unicode_` | Fixed-length Unicode |

Convert data types using:

In [6]:
print(array.astype(np.float64))

[1. 2. 3. 4.]


### Saving and Loading Arrays

In [ ]:
np.save('my_array.npy', arr)         # Save binary
np.load('my_array.npy')              # Load binary

np.savetxt('my_file.txt', arr, delimiter=',')   # Save text
np.loadtxt('my_file.txt', delimiter=',')        # Load text
np.genfromtxt('file.csv', delimiter=',')        # More flexible loading

We can also save multiple arrays in compressed `.npz` format:

In [ ]:
np.savez('data.npz', a=arr1, b=arr2)
data = np.load('data.npz')
print(data['a'])  # Access saved arrays

### Summary

NumPy is the backbone of scientific computing in Python, and mastering it is essential for anyone pursuing data science, AI, or machine learning. It offers a powerful `ndarray` object that lets us store and manipulate structured numerical data much more efficiently than Python lists. Whether we're working with 1D arrays (like vectors) or 2D and higher-dimensional arrays (like matrices), NumPy provides clean and efficient tools.

In this first step of our journey, we’ve explored what makes NumPy special. We’ve seen how to create arrays using Python lists and a variety of built-in NumPy functions like `zeros()`, `ones()`, `arange()`, `full()`, `eye()`, and even generate random arrays with `random.random()`. We’ve also learned about NumPy's efficient storage system and how it uses less memory by enforcing fixed data types. We can check array properties like shape, size, number of dimensions, and data types easily with simple attributes.

Most importantly, NumPy allows us to save and load our work in both binary and text formats using functions like `save()`, `load()`, `savetxt()`, and `genfromtxt()`. This makes it easy to persist and reuse our data — an important part of building real-world AI projects.