# Linear Algebra in NumPy

### What is Linear Algebra?

Linear algebra is the branch of mathematics that helps us understand and work with structured numerical data. It deals with vectors (which are like one-dimensional lists of numbers), matrices (which are like tables or grids of numbers), and higher-dimensional arrays. These structures are used to represent data, relationships, and transformations — which are all critical in fields like machine learning, computer graphics, and AI.

We use linear algebra to handle tasks like rotating images, transforming datasets, compressing information, and solving systems of equations. In machine learning, almost everything — from data input to model weights to predictions — is represented as vectors and matrices. When we train models, we're often multiplying matrices together, adjusting weights, and analyzing patterns. The math behind this — vector addition, matrix multiplication, transposition, inversion, and eigen decomposition — is all part of linear algebra.

Understanding these operations helps us design algorithms, optimize performance, and extract insights from data. Whether it's recognizing faces in images, predicting stock prices, or translating text, the foundation is often built using the concepts of linear algebra

### Key Concepts & Operations in Linear Algebra

1. **Dot Product (`np.dot()` or `@`)**
    
    The dot product is an operation where we multiply corresponding elements of two arrays and sum the result. This operation is used in many AI models to calculate similarity between vectors or to combine inputs with weights.

In [1]:
import numpy as np
    
a = np.array([1, 2])
b = np.array([3, 4])
    
dot = np.dot(a, b)  # or a @ b
print("Dot Product:", dot)

Dot Product: 11


2. **Matrix Multiplication (`np.matmul()` or `@`)**
    
    Matrix multiplication lets us combine rows of one matrix with columns of another. This is the backbone of all neural network computations — inputs get multiplied by weights layer by layer.

In [2]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
    
result = np.matmul(A, B)
print("Matrix Multiplication:\n", result)

Matrix Multiplication:
 [[19 22]
 [43 50]]


3. **Transpose of a Matrix (`.T` or `np.transpose()`)**
    
    Transposing a matrix means flipping its rows and columns. We often do this when reshaping data or preparing matrices for multiplication.

In [3]:
matrix = np.array([[1, 2], [3, 4]])
transposed = matrix.T
print(transposed)

[[1 3]
 [2 4]]


4. **Inverse of a Matrix (`np.linalg.inv()`)**
    
    The inverse of a matrix is the equivalent of "dividing" by that matrix. Only square matrices that are non-singular (i.e., have a non-zero determinant) have an inverse.

In [4]:
from numpy.linalg import inv
    
A = np.array([[1, 2], [3, 4]])
A_inv = inv(A)
print("Inverse:\n", A_inv)

Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]


5. **Determinant (`np.linalg.det()`)**
    
    The determinant is a scalar value that tells us if a matrix is invertible. If the determinant is zero, the matrix can’t be inverted.

In [5]:
from numpy.linalg import det
    
A = np.array([[1, 2], [3, 4]])
print("Determinant:", det(A))

Determinant: -2.0000000000000004


6. **Eigenvalues & Eigenvectors (`np.linalg.eig()`)**
    
    These represent the "direction" and "scale" of how data is transformed. We use them in dimensionality reduction techniques like PCA.

In [6]:
from numpy.linalg import eig
    
A = np.array([[4, -2], [1, 1]])
vals, vecs = eig(A)
print("Eigenvalues:\n", vals)
print("Eigenvectors:\n", vecs)

Eigenvalues:
 [3. 2.]
Eigenvectors:
 [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


### AI/ML Use Cases of Linear Algebra

| Linear Algebra Concept | Real-World Use Case |
| --- | --- |
| Dot Product | Similarity Search, Attention |
| Matrix Multiplication | Neural Networks, Word Embeddings |
| Transpose | Tensor Reshaping |
| Inverse Matrix | Optimization, Solving Equations |
| Eigenvalues/Vectors | PCA, Dimensionality Reduction |
| Determinant | Invertibility Checks |

### Exercises

Q1. Compute the dot product of two vectors: `[1, 2, 3]` and `[4, 5, 6]`

In [7]:
a = np.array([1,2,3])
b = np.array([4,5,6])

dot_pro1 = np.dot(a, b)
dot_pro2 = a @ b
print(f'Using np.dot(): {dot_pro1}')
print(f'Using @ operator: {dot_pro2}')

Using np.dot(): 32
Using @ operator: 32


Q2. Multiply two 2x2 matrices using `@` operator.

In [8]:
c = np.array([[20,30], [40,50]])
d = np.array([[60,70], [80,90]])

matrix_multiplication = c @ d
print(f'Matrix Multiplication Result:\n{matrix_multiplication}')

Matrix Multiplication Result:
[[3600 4100]
 [6400 7300]]


Q3. Find the transpose and inverse of `[[2, 1], [5, 3]]`

In [9]:
e = np.array([[2, 1], [5, 3]])
tarnsposed = e.T
print('Transpose:\n',tarnsposed)

Transpose:
 [[2 5]
 [1 3]]


Q4. Find the determinant and eigenvalues of matrix `[[1, 2], [2, 1]]`

In [10]:
from numpy.linalg import eig

f = np.array([[1, 2], [2, 1]])
eigenvalues, eigenvectors = eig(f)
print('Eigenvalues:\n', eigenvalues)
print('Eigenvectors:\n', eigenvectors)

Eigenvalues:
 [ 3. -1.]
Eigenvectors:
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


Q5. Create a matrix `A` and verify if `A @ A_inv = I` (identity matrix)

In [11]:
from numpy.linalg import inv

A = np.array([[1, 2], [3, 4]])

A_inv = np.linalg.inv(A)

# Float result of A @ A_inv
identity_float = A @ A_inv
print("Identity Matrix (float result):\n", identity_float)

# Rounded to nearest integer for clean display
identity_int = np.rint(identity_float).astype(int)
print("Identity Matrix (rounded to int):\n", identity_int)

Identity Matrix (float result):
 [[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]
Identity Matrix (rounded to int):
 [[1 0]
 [0 1]]


### Summary

Linear Algebra plays a central role in modern machine learning, data science, and AI workflows. It helps us represent and transform data using vectors and matrices. With NumPy, we can perform all key linear algebra operations like dot products, matrix multiplication, transpose, inverse, determinant, and eigen decomposition — all essential tools when working with high-dimensional datasets and neural networks.

The dot product is widely used for calculating similarity, projecting vectors, and building neural network operations. Matrix multiplication is the foundation of linear layers, while the transpose lets us align dimensions for valid multiplications. The inverse helps solve equations in optimization problems. The determinant gives insight into a matrix’s properties, like whether it's invertible. Eigenvalues and eigenvectors help us reduce dimensionality and understand the underlying structure of data through techniques like PCA.

By learning these operations in NumPy, we can build powerful models and perform numerical computations with ease. These concepts not only help us manipulate data efficiently but also form the theoretical base of algorithms that power real-world AI systems. Understanding how these matrix-based transformations work gives us better control over model behavior, optimization, and interpretability — all of which are crucial for developing intelligent, robust solutions.