# Random Number Generation in NumPy

### What is Random Number Generation?

When we talk about random number generation, we mean creating values that are unpredictable or follow a probability distribution. In NumPy, we use this concept to simulate real-world scenarios, prepare datasets, and build intelligent systems. The `np.random` module gives us powerful tools to generate random values such as floats, integers, or samples from distributions like uniform or normal.

We rely on randomness for tasks like training/testing data splits, initializing model weights, simulating rare cases, or shuffling training batches. Since most randomness in programming is pseudo-random (generated using algorithms), NumPy allows us to control it using `np.random.seed()` — ensuring our results are repeatable and reliable.

### Basic Random Generators in `np.random`

1. Random Floats in [0,1)

In [1]:
import numpy as np
    
random_floats = np.random.rand(5)
print(random_floats)

[0.62072827 0.31172415 0.14888059 0.23720541 0.18024249]


2. Random Integers (Uniform Distribution)

In [2]:
rand_ints = np.random.randint(1, 10, size=(3, 3))
print(rand_ints)

[[5 3 1]
 [2 2 5]
 [2 5 5]]


3. Normal Distribution (mean=0, std=1)

In [3]:
normal_data = np.random.randn(100)
print("Mean:", np.mean(normal_data))
print("Standard Deviation:", np.std(normal_data))

Mean: -0.11094400346607065
Standard Deviation: 0.935027116329924


### Reproducibility with `np.random.seed()`

We use `np.random.seed()` when we want our code to behave **exactly the same** every time we run it — especially useful in testing and model tuning.

In [4]:
np.random.seed(42)
print(np.random.rand(3))

[0.37454012 0.95071431 0.73199394]


### Random Shuffling and Permutation

1. Shuffle In-Place

In [5]:
arr = np.array([1, 2, 3, 4, 5])
np.random.shuffle(arr)
print(arr)

[4 2 3 1 5]


2. Return a Shuffled Copy

In [6]:
arr = np.array([10, 20, 30, 40])
shuffled = np.random.permutation(arr)
print("Original:", arr)
print("Shuffled:", shuffled)

Original: [10 20 30 40]
Shuffled: [20 10 40 30]


### Random Samples from Custom Distributions

1.  Normal Distribution with Custom Mean/Std

In [7]:
normal = np.random.normal(loc=0, scale=1, size=10)
print("Normal Distribution Sample:", normal)

Normal Distribution Sample: [-2.01096289 -0.49280342  0.39257975 -0.92918467  0.07983181 -0.1595165
  0.02222183 -0.42779291 -0.53181741 -0.1174755 ]


2. Uniform Distribution from a Rang

In [8]:
uniform = np.random.uniform(low=5, high=10, size=5)
print("Uniform Distribution Sample:", uniform)

Uniform Distribution Sample: [9.86877759 6.1638567  5.45303217 8.09193005 6.91230996]


### Random Choice from a List or Array

In [9]:
names = ['Sujit', 'Ram', 'Ravi', 'Anjali']
chosen = np.random.choice(names, size=2)
print(chosen)

['Anjali' 'Anjali']


### Why It Matters in AI/ML

Random numbers are part of almost every AI workflow we work with. They help us:

- Split datasets into **training and testing sets**
- Initialize **neural network weights** with randomness
- Simulate synthetic data when we lack real-world samples
- Shuffle datasets to avoid overfitting
- Add noise to make models more **generalizable**
- Use `np.random.seed()` to **reproduce experiments** for consistent debugging

Whether we’re training a deep learning model or just exploring data, randomness keeps our work **unbiased, flexible, and powerful**.

### Exercises

Q1. Generate a 1D array of 10 random floats between 0 and 1.

In [10]:
arr = np.random.rand(10)
print("Random Floats (0 to 1):", arr)


Random Floats (0 to 1): [0.46676289 0.85994041 0.68030754 0.45049925 0.01326496 0.94220176
 0.56328822 0.3854165  0.01596625 0.23089383]


Q2. Create a 4×4 matrix of random integers between 10 and 100.

In [11]:
matrix = np.random.randint(10, 100, size=(4, 4))
print(matrix)

[[69 80 53 17]
 [56 44 87 90]
 [45 59 13 11]
 [15 63 13 63]]


Q3. Generate 1000 values from a normal distribution with mean = 5 and std = 2. Find their mean and std.

In [12]:
# Generate 1000 values from a normal distribution (mean=5, std=2)
data = np.random.normal(loc=5, scale=2, size=1000)

# Calculate the mean and standard deviation of the generated data
mean = np.mean(data)
std_dev = np.std(data)

print("Sample Mean:", mean)
print("Sample Standard Deviation:", std_dev)

Sample Mean: 5.103095308885288
Sample Standard Deviation: 2.0759947016224602


Q4. Shuffle a list of integers from 1 to 10 and print both original and shuffled versions.

In [13]:
# Original list
original = np.arange(1, 11)
print("Original list:", original)

# Shuffled list
shuffled = original.copy()
np.random.shuffle(shuffled)
print("Shuffled list:", shuffled)

Original list: [ 1  2  3  4  5  6  7  8  9 10]
Shuffled list: [ 1  6 10  2  4  3  9  5  7  8]


Q5. Set a random seed and generate the same 5 random integers twice to prove reproducibility.

In [14]:
np.random.seed(42)

# Generate 5 random integers between 1 and 100
random_integers_1 = np.random.randint(1, 101, size=5)
print("First set:", random_integers_1)

# Reset the seed to get the same result
np.random.seed(42)
random_integers_2 = np.random.randint(1, 101, size=5)
print("Second set:", random_integers_2)

First set: [52 93 15 72 61]
Second set: [52 93 15 72 61]


### Summary

Understanding how to generate and control randomness is crucial. Random number generation in NumPy helps us simulate real-world conditions, train reliable models, and ensure that our results can be repeated. We use it to create synthetic datasets, initialize weights in models, shuffle inputs, and inject noise — all of which help our models learn better and generalize well.

By using functions like `np.random.rand()`, `np.random.randint()`, `np.random.normal()`, and `np.random.uniform()`, we can generate values for testing or training in any shape or range. For example, we might generate a 2D array of random integers to simulate pixel data, or draw from a normal distribution to create features with realistic variance. We can also sample from custom distributions or lists using `np.random.choice()`.

For reproducibility — a key part of any serious ML experiment — we use `np.random.seed()` to make sure our randomness stays consistent each time we rerun the code. Functions like `shuffle()` and `permutation()` help us reorder data safely.

Overall, mastering NumPy’s random tools gives us flexibility and control — two essential qualities for building robust, intelligent systems. With these tools, we’re not just relying on randomness — we’re engineering it for insight and innovation.