# Stacking & Splitting Arrays in NumPy

### What Are Stacking & Splitting?

When we work with data in NumPy, especially in AI and ML, we often need to **combine multiple arrays** into one or **split a large array** into smaller pieces. This helps us organize our data the way our models and algorithms expect.

- **Stacking** means we’re joining multiple arrays together — side by side (horizontal), top to bottom (vertical), or even deeper (like 3D).
- **Splitting** means we’re taking a big array and breaking it into smaller chunks — row-wise, column-wise, or by depth.

These tools help us prepare training data, group features, manage batches, handle image channels, and more. Once we’re good at stacking and splitting, reshaping data becomes smooth and flexible across our entire ML pipeline.

### Key Operations (Stack)

1. **Horizontal Stack – `np.hstack()`**
    
    This stacks arrays **side by side**. We use it when the number of **rows is the same**, and we want to extend the **columns**.

In [1]:
import numpy as np
    
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
    
h_stacked = np.hstack((a, b))
print("Horizontal Stack:\n", h_stacked)

Horizontal Stack:
 [[1 2 5 6]
 [3 4 7 8]]


2. **Vertical Stack – `np.vstack()`**

    This stacks arrays **on top of each other**. Here, the number of **columns must match**, and it adds more **rows**.

In [2]:
v_stacked = np.vstack((a, b))
print("Vertical Stack:\n", v_stacked)

Vertical Stack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


3. **Depth Stack – `np.dstack()`**

    This stacks arrays along the **third axis (depth)** — perfect when we want to make 3D arrays.

In [3]:
d_stacked = np.dstack((a, b))
print("Depth Stack:\n", d_stacked)

Depth Stack:
 [[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


4. **Stack – `np.stack()`**

    This is the most flexible stack. We can choose **which axis** to stack on (axis=0, 1, or 2). It creates a new dimension.

In [4]:
stacked0 = np.stack((a, b), axis=0)
stacked1 = np.stack((a, b), axis=1)
    
print("Stacked along axis 0:\n", stacked0)
print("Stacked along axis 1:\n", stacked1)

Stacked along axis 0:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Stacked along axis 1:
 [[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


### Key Operations (Split)

1. **Horizontal Split – `np.hsplit()`**

    We can split an array **column-wise**. It breaks the array into chunks **horizontally**.

In [5]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
hsplit = np.hsplit(arr, 2)
print("Horizontal Split:\n", hsplit)

Horizontal Split:
 [array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]


2. **Vertical Split – `np.vsplit()`**

    We split the array **row-wise** — breaking it into vertical sections.

In [6]:
vsplit = np.vsplit(arr, 2)
print("Vertical Split:\n", vsplit)

Vertical Split:
 [array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]


3. **Depth Split – `np.dsplit()`**
    
    This works on **3D arrays** and splits them along the **depth/channel axis**.

In [7]:
arr_3d = np.dstack((a, b))
dsplit = np.dsplit(arr_3d, 2)
print("Depth Split:\n", dsplit)

Depth Split:
 [array([[[1],
        [2]],

       [[3],
        [4]]]), array([[[5],
        [6]],

       [[7],
        [8]]])]


### AI/ML Use Cases

| Operation | How We Use It in AI/ML |
| --- | --- |
| `hstack()` | Combine features from different arrays |
| `vstack()` | Add more samples (rows) to our dataset |
| `dstack()` | Stack channels (RGB or feature maps) |
| `stack()` | Add batch or channel dimension for models |
| `hsplit()` | Break features apart (e.g. split input/output columns) |
| `vsplit()` | Make mini-batches from a large dataset |
| `dsplit()` | Separate channels or feature layers |

### Exercises

Q1.  Horizontally stack two 2x2 arrays.

In [8]:
a = np.array([[1, 2], [3, 4]])  
b = np.array([[5, 6], [7, 8]])

h_stacked = np.hstack((a, b))
print("Horizontal Stack:\n", h_stacked)

Horizontal Stack:
 [[1 2 5 6]
 [3 4 7 8]]


Q2. Vertically stack two 1-row arrays.

In [9]:
a = np.array([[10, 20]])  
b = np.array([[30, 40]])

v_stacked = np.vstack((a, b))
print("Vertical Stack:\n", v_stacked)

Vertical Stack:
 [[10 20]
 [30 40]]


Q3. Use np.stack() to combine two arrays using axis 0 and axis 1. Print their shapes.

In [10]:
a = np.array([[4, 5], [6, 7]])
b = np.array([[8, 9], [10, 11]])

stacked0 = np.stack((a, b), axis=0)
stacked1 = np.stack((a, b), axis=1)

print("Shape when stacked along axis 0:", stacked0.shape)
print("Shape when stacked along axis 1:", stacked1.shape)

Shape when stacked along axis 0: (2, 2, 2)
Shape when stacked along axis 1: (2, 2, 2)


Q4. Horizontally split a 2x4 array into two equal parts.

In [11]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
hsplit = np.hsplit(arr, 2)

print("Horizontal Split:\n", hsplit)

Horizontal Split:
 [array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]


Q5. Create a 3D array using dstack() and split it using dsplit().

In [12]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

arr_3d = np.dstack((a, b))
dsplit = np.dsplit(arr_3d, 2)

print("3D Array using dstack():\n", arr_3d)
print("Split 3D Array using dsplit():\n", dsplit)

3D Array using dstack():
 [[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]
Split 3D Array using dsplit():
 [array([[[1],
        [2]],

       [[3],
        [4]]]), array([[[5],
        [6]],

       [[7],
        [8]]])]


### Summary

Stacking and splitting arrays gives us powerful ways to shape our data exactly how we need it. Whether we’re combining features, joining data, or breaking datasets into parts, NumPy’s stacking and splitting tools help us control data structure with precision.

- We use **`hstack()`** to add more columns (side by side).
- We use **`vstack()`** to add more rows (top to bottom).
- We use **`dstack()`** and **`stack()`** when working with 3D data or models that need extra dimensions.
- We use **`hsplit()`**, **`vsplit()`**, and **`dsplit()`** to break data into chunks — for training, testing, batching, or feature engineering.

By mastering these, we make sure our data is always in the right shape for models, layers, visualizations, and preprocessing. It’s one more step toward becoming solid in data manipulation and AI development.