# Transposing, Flattening & Resizing Arrays in NumPy

### What Are Transposing, Flattening & Resizing?

When working with multidimensional data in NumPy, we often need to **reorganize the shape or structure** of arrays for mathematical operations or machine learning workflows. NumPy makes it easy to **transpose, flatten, and resize arrays** so they match the expected input/output formats of algorithms and models.

- **Transposing** means flipping an array along its diagonal — rows become columns and columns become rows.
- **Flattening** means converting a multi-dimensional array (like 2D or 3D) into a 1D array.
- **Resizing** changes the shape of the array to new dimensions (as long as the total number of elements remains the same).

These operations are especially useful in deep learning (reshaping tensors), image processing (flattening RGB matrices), and data preprocessing (transforming tables for model input).

### Key Operations

1. **Transpose (`.T` or `np.transpose()`)**
    
    Transposing flips an array's rows and columns. In 2D arrays, it's a simple matrix transpose. For higher dimensions, we can specify axes to permute.

In [1]:
import numpy as np
    
arr = np.array([[1, 2, 3], [4, 5, 6]])
transposed = arr.T
print("Transposed:\n", transposed)

Transposed:
 [[1 4]
 [2 5]
 [3 6]]


2. **Flatten (`.flatten()` or `np.ravel()`)**
    
    Flattening reduces a multi-dimensional array to a 1D array. This is commonly done before feeding image data into a neural network or converting matrices into feature vectors.

In [2]:
arr = np.array([[1, 2], [3, 4]])
flat = arr.flatten()
print("Flattened:", flat)

Flattened: [1 2 3 4]


3. **Reshape (`.reshape(new_shape)`)**
    
    Reshaping changes the shape of an array without changing its data. The new shape must match the total number of elements.

In [3]:
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped = arr.reshape((2, 3))
print("Reshaped:\n", reshaped)

Reshaped:
 [[1 2 3]
 [4 5 6]]


4. **Resize (`np.resize()` or `.resize()`)**
    
    Unlike `reshape()`, which only works with the same number of elements, `resize()` can also **add or cut elements**, filling with repeating data if needed.

In [4]:
arr = np.array([1, 2, 3])
resized = np.resize(arr, (2, 4))
print("Resized:\n", resized)

Resized:
 [[1 2 3 1]
 [2 3 1 2]]


### AI/ML Use Cases

| Operation | Real-World Use Case |
| --- | --- |
| Transpose | Matrix alignment in backpropagation |
| Flatten | Flattening image data for neural networks |
| Reshape | Preparing input/output shapes for layers |
| Resize | Adjusting data shape in preprocessing pipelines |

### Exercises

Q1. Transpose a 3x2 matrix and observe the result.

In [5]:
arr = np.array([[2,4], [8,10], [14,16]])
T_arr = np.transpose(arr)

print("Original array:")
print(arr)

print("\nTransposed array:")

Original array:
[[ 2  4]
 [ 8 10]
 [14 16]]

Transposed array:


Q2. Create a 2x3 array and flatten it using both `.flatten()` and `np.ravel()`

In [6]:
arr = np.array([[2,6,10], [4,8,12]])

F_arr = arr.flatten()
rav_arr = np.ravel(arr)

print("\nOriginal array:")
print(arr)

print("\nFlattened array:")
print(F_arr)

print("\nRaveled array:")
print(rav_arr)


Original array:
[[ 2  6 10]
 [ 4  8 12]]

Flattened array:
[ 2  6 10  4  8 12]

Raveled array:
[ 2  6 10  4  8 12]


Q3. Create a 1D array with 12 elements and reshape it into a 3x4 matrix.

In [7]:
arr = np.array([5,6,7,8,9,6,5,4,3,2,1,4])
reshaped_arr = arr.reshape(3, 4)

print("\nOriginal array:")
print(arr)

print("\nReshaped array:")
print(reshaped_arr)


Original array:
[5 6 7 8 9 6 5 4 3 2 1 4]

Reshaped array:
[[5 6 7 8]
 [9 6 5 4]
 [3 2 1 4]]


Q4. Use `np.resize()` to resize a 1D array of 5 elements into a 2x4 array.

In [8]:
arr = np.array([5,6,7,8,9])
resized_arr = np.resize(arr, (2, 4))

print("Original array:")
print(arr)

print("Resized array:")
print(resized_arr)

Original array:
[5 6 7 8 9]
Resized array:
[[5 6 7 8]
 [9 5 6 7]]


### Summary

Transposing, flattening, and resizing are powerful operations in NumPy that help structure data correctly for machine learning and data analysis tasks. Transposing is essential for aligning dimensions in matrix multiplication or gradient calculation. Flattening is commonly used when converting multidimensional data (like images) into 1D vectors for input into models. Reshaping is fundamental when converting input/output into forms expected by different algorithms or neural network layers. Resizing goes a step further by altering array size even when element count changes.

Together, these tools give us flexibility and control over how we prepare and process data. Mastering them ensures that our AI/ML models receive data in the correct shape — reducing bugs, boosting performance, and enabling smooth experimentation.